# Site settings
title: How to Train Your Data
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Data Science blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seiteta.github.io" # the base hostname & protocol for your site
twitter_username: seiteta
github_username:  seiteta

# Build settings
markdown: kramdown
